-- =============================================
-- AI Support Ticket System - Database Schema
-- =============================================

CREATE DATABASE IF NOT EXISTS support_ticket_db;
USE support_ticket_db;

-- Users table (all 3 roles: customer, agent, admin)
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('customer', 'agent', 'admin') NOT NULL DEFAULT 'customer',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tickets table
CREATE TABLE tickets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ticket_number VARCHAR(20) NOT NULL UNIQUE,   -- e.g. TKT-00001
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,

    -- Human-set fields
    category ENUM('technical', 'billing', 'general', 'feature_request', 'other') NOT NULL DEFAULT 'general',
    priority ENUM('low', 'medium', 'high', 'urgent') NOT NULL DEFAULT 'medium',
    status ENUM('open', 'in_progress', 'resolved', 'closed') NOT NULL DEFAULT 'open',

    -- AI-suggested fields (stored separately so agent can compare & override)
    ai_suggested_category VARCHAR(50),
    ai_suggested_priority VARCHAR(20),

    -- Relationships
    customer_id INT NOT NULL,
    assigned_agent_id INT,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP NULL,

    FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_agent_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Responses / messages on a ticket
CREATE TABLE responses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ticket_id INT NOT NULL,
    responder_id INT NOT NULL,
    message TEXT NOT NULL,
    is_ai_draft BOOLEAN NOT NULL DEFAULT FALSE,      -- was this generated by AI?
    is_internal_note BOOLEAN NOT NULL DEFAULT FALSE, -- agent-only note, customer can't see
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,
    FOREIGN KEY (responder_id) REFERENCES users(id) ON DELETE CASCADE
);

-- AI usage log (for admin dashboard - tokens used, actions taken)
CREATE TABLE ai_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ticket_id INT NOT NULL,
    action ENUM('classify', 'draft_response') NOT NULL,
    prompt_tokens INT DEFAULT 0,
    completion_tokens INT DEFAULT 0,
    ai_output TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE
);

-- Email notification log (track what was sent)
CREATE TABLE email_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    recipient_email VARCHAR(150) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    status ENUM('sent', 'failed') NOT NULL DEFAULT 'sent',
    ticket_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE SET NULL
);

-- =============================================
-- Seed data: default admin account
-- Password: Admin@123 (bcrypt hashed - update this after running app)
-- =============================================
INSERT INTO users (name, email, password_hash, role) VALUES
('Admin', 'admin@support.com', 'REPLACE_WITH_BCRYPT_HASH', 'admin');
